# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_ebrel_cpp <- function(E_int, C, SD, D, SxH, O, action_weight, LM_int, X0, dim_x, dim_y, n_actions, n_species, sentinel, opt) {
    .Call(`_ebrel2_run_ebrel_cpp`, E_int, C, SD, D, SxH, O, action_weight, LM_int, X0, dim_x, dim_y, n_actions, n_species, sentinel, opt)
}

generate_X0_CI_R <- function(U, n_actions, dim_x, dim_y, base_prob, seed) {
    .Call(`_ebrel2_generate_X0_CI_R`, U, n_actions, dim_x, dim_y, base_prob, seed)
}

ebrel_omp_thread_limit <- function() {
    .Call(`_ebrel2_ebrel_omp_thread_limit`)
}

ebrel_omp_for_threads <- function() {
    .Call(`_ebrel2_ebrel_omp_for_threads`)
}

